In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = np.random.randint(0, 100, (10 ,2))

In [3]:
data

array([[ 9, 26],
       [27,  0],
       [64, 66],
       [70, 87],
       [69, 45],
       [12,  6],
       [94, 17],
       [16, 16],
       [15,  0],
       [95, 53]])

In [4]:
scaler_model = MinMaxScaler()

In [5]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [6]:
scaler_model.fit(data)

C:\Users\sid\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data)

array([[0.        , 0.29885057],
       [0.20930233, 0.        ],
       [0.63953488, 0.75862069],
       [0.70930233, 1.        ],
       [0.69767442, 0.51724138],
       [0.03488372, 0.06896552],
       [0.98837209, 0.1954023 ],
       [0.08139535, 0.18390805],
       [0.06976744, 0.        ],
       [1.        , 0.6091954 ]])

In [8]:
import pandas  as pd

In [9]:
mydata = np.random.randint(0, 101 , (50 ,4))

In [10]:
mydata

array([[  6,   7,  36,  27],
       [ 17,  79,  40,  45],
       [ 37,  15,  14,  82],
       [ 87,  85,   3,  70],
       [ 77,  93,  52,  93],
       [ 94,  96,  54,  70],
       [ 49,  16,   0,  48],
       [ 84,  67,  85,  27],
       [ 68,   2,  86,  84],
       [ 51,  72,  71,  85],
       [  7,  89,  52,  10],
       [ 27,  78,  22,  78],
       [ 78,  81,  87,  38],
       [ 37,  58,   0,  13],
       [ 13,  64,  98,  34],
       [ 63,  56,   3,  63],
       [ 98,  88,  20,  26],
       [ 65,  91,  84,  13],
       [ 79,   8,  57,  28],
       [ 94,  95,  80,  98],
       [ 22,  80,  57,  63],
       [ 95,  13,  66,  68],
       [ 95,  67,  43,  81],
       [ 57,  38,  78,  92],
       [ 55,  97,   0,  30],
       [ 59,  89,  95,  35],
       [ 46,  13,  90,  35],
       [ 34,  54,  64,  99],
       [ 69,  19,   2,  25],
       [ 71,  13,  25,  19],
       [ 69,  15,  96,  99],
       [ 33, 100,  65,  31],
       [ 54,  18,  71,   9],
       [ 59,  90,  28,  53],
       [ 88,  

In [13]:
data = pd.DataFrame(data = mydata, columns = ['f1', 'f2', 'f3', 'label'])

In [14]:
data

f1   f2   f3  label
0     6    7   36     27
1    17   79   40     45
2    37   15   14     82
3    87   85    3     70
4    77   93   52     93
5    94   96   54     70
6    49   16    0     48
7    84   67   85     27
8    68    2   86     84
9    51   72   71     85
10    7   89   52     10
11   27   78   22     78
12   78   81   87     38
13   37   58    0     13
14   13   64   98     34
15   63   56    3     63
16   98   88   20     26
17   65   91   84     13
18   79    8   57     28
19   94   95   80     98
20   22   80   57     63
21   95   13   66     68
22   95   67   43     81
23   57   38   78     92
24   55   97    0     30
25   59   89   95     35
26   46   13   90     35
27   34   54   64     99
28   69   19    2     25
29   71   13   25     19
30   69   15   96     99
31   33  100   65     31
32   54   18   71      9
33   59   90   28     53
34   88   27   91     35
35   89   84  100     97
36    6   84   33     22
37   36    9   88     74
38  100   10   95     20
39    3   14   94     96
40   41   70   67     39
41   39   67   95     62
42    0   71   59     59
43   76   62   70     34
44   49   60   23     57
45   58   24   64     18
46   61   31   20     98
47   42   91   22     22
48   83   86   75     97
49   73   19   38     48

In [16]:
x = data[['f1', 'f2', 'f3']]

In [18]:
y = data['label']

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y,
                                test_size=0.3, random_state=101)

In [20]:
x_train.shape

(35, 3)

In [21]:
x_test.shape

(15, 3)